services:
  devopsdb:
    container_name: devopsdb
    build:
      context: ./Docker-db
    ports:
      - "3306:3306"

  application:
    container_name: containerapp
    build:
      context: ./Docker-app
    ports:
      - "1234:8080"
    depends_on:
      - devopsdb
